broker.url=tcp://localhost:61616
client.id=business-unit
topics=CommodityPrice,Weather

event.store.path=eventstore

batch.datamart.url=jdbc:sqlite:businessunit_batch.db
serving.datamart.url=jdbc:sqlite:businessunit_serving.db

api.port=7070

ml.api.url=http://localhost:8000
speed.layer.debounce.seconds=5